version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapi
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # API .NET
  todoapi:
    build:
      context: .
      dockerfile: Dockerfile.new
    container_name: todo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=todoapi;Uid=root;Pwd=rootpassword;
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped

  # Application Angular
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    container_name: todo-angular-app
    ports:
      - "3000:80"
    depends_on:
      - todoapi
    networks:
      - todo-network
    restart: unless-stopped

  # Interface PhpMyAdmin (optionnel)
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: todo-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
    driver: bridge